### ISSUE TITLE
tuya adapter nicht configuribar 

### ISSUE THREAD

**Issue by kakacs** [Apollon77/ioBroker.tuya#240]
Hallo hab heute iobroker auf mein raspberry pi 4 installiert und will den tuya adaptar installieren ich mach das so wie es es in den brschreibungen sind ich nutze ein iphone 12 mit der tuya app ich lade das zertifikat über den qr code runter uns insatllier das in meinem iphone. stelle in meinem wlan den proxy ein ip vm iobroker un port 8888 .
dann starte ich die ich die tuyap im handy es kommt die meldung.

Überpr.Sie die Zeiteinst.in ihrem Telefon um sicherzust. das sie mit Ihrer Ortszeit und Zeitzone übereinst.

was kann das problem sein 

2020-12-19 23:25:34.166  - error:  tuya.0 (1949) SSL-Proxy ERROR: Error: 3069413840:error:14209102:SSL  routines:tls_early_post_process_client_hello:unsupported  protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
--
2020-12-19 23:25:34.167  - error:  tuya.0 (1949) Error: 3069413840:error:14209102:SSL  routines:tls_early_post_process_client_hello:unsupported  protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
2020-12-19 23:25:47.144  - error: tuya.0 (1949) SSL-Proxy ERROR: Error: socket hang up
2020-12-19 23:25:47.146  - error: tuya.0 (1949) Error: socket hang up
at connResetException (internal/errors.js:609:14)
at TLSSocket.onSocketClose (_tls_wrap.js:1063:23)
at TLSSocket.emit (events.js:326:22)
at TLSSocket.EventEmitter.emit (domain.js:483:12)
at net.js:675:12
at Socket.done (_tls_wrap.js:568:7)
at Object.onceWrapper (events.js:421:26)
at Socket.emit (events.js:314:20)
at Socket.EventEmitter.emit (domain.js:483:12)
at TCP. (net.js:675:12)
2020-12-19 23:26:31.771  - error: tuya.0 (1949) SSL-Proxy ERROR: Error: socket hang up
2020-12-19 23:26:31.774  - error: tuya.0 (1949) Error: socket hang up

**Comment by Apollon77** [comment]
iphone 12? How you istalled the required old app version? 

> The Adapter only works with Tuya and compatible apps as long as their version is <3.14 (!!)

best way might be android emulator
