### ISSUE TITLE
3.6.0 uncaught exception...

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.tuya#272]
with Version 3.6.0 I found this in the logfile:
`2021-04-03 10:52:10.797  - error: tuya.0 (7124) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-04-03 10:52:10.798  - error: tuya.0 (7124) unhandled promise rejection: connection timed out
2021-04-03 10:52:10.799  - error: tuya.0 (7124) Error: connection timed out
    at Socket.<anonymous> (/opt/iobroker/node_modules/tuyapi/index.js:440:18)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2021-04-03 10:52:10.800  - error: tuya.0 (7124) connection timed out
2021-04-03 10:52:10.797  - error: tuya.0 (7124) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-04-03 10:52:10.798  - error: tuya.0 (7124) unhandled promise rejection: connection timed out
2021-04-03 10:52:10.799  - error: tuya.0 (7124) Error: connection timed out
    at Socket.<anonymous> (/opt/iobroker/node_modules/tuyapi/index.js:440:18)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2021-04-03 10:52:10.800  - error: tuya.0 (7124) connection timed out
2021-04-03 10:52:11.827  - warn: tuya.0 (7124) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-04-03 10:52:11.827  - warn: tuya.0 (7124) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-04-03 10:52:12.587  - info: linux-control.0 (5918) successful received data from zigberry (192.168.4.21:22)
2021-04-03 10:52:12.894  - error: host.VMC123-iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2021-04-03 10:52:12.895  - error: host.VMC123-iobroker Caught by controller[1]: Error: connection timed out
2021-04-03 10:52:12.895  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket.<anonymous> (/opt/iobroker/node_modules/tuyapi/index.js:440:18)
2021-04-03 10:52:12.895  - error: host.VMC123-iobroker Caught by controller[1]:     at Object.onceWrapper (events.js:421:28)
2021-04-03 10:52:12.895  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket.emit (events.js:315:20)
2021-04-03 10:52:12.895  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket.EventEmitter.emit (domain.js:467:12)
2021-04-03 10:52:12.896  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket._onTimeout (net.js:483:8)
2021-04-03 10:52:12.896  - error: host.VMC123-iobroker Caught by controller[1]:     at listOnTimeout (internal/timers.js:554:17)
2021-04-03 10:52:12.896  - error: host.VMC123-iobroker Caught by controller[1]:     at processTimers (internal/timers.js:497:7)
2021-04-03 10:52:12.896  - error: host.VMC123-iobroker instance system.adapter.tuya.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-04-03 10:52:12.897  - info: host.VMC123-iobroker Restart adapter system.adapter.tuya.0 because enabled
2021-04-03 10:52:12.587  - info: linux-control.0 (5918) successful received data from zigberry (192.168.4.21:22)
2021-04-03 10:52:12.894  - error: host.VMC123-iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2021-04-03 10:52:12.895  - error: host.VMC123-iobroker Caught by controller[1]: Error: connection timed out
2021-04-03 10:52:12.895  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket.<anonymous> (/opt/iobroker/node_modules/tuyapi/index.js:440:18)
2021-04-03 10:52:12.895  - error: host.VMC123-iobroker Caught by controller[1]:     at Object.onceWrapper (events.js:421:28)
2021-04-03 10:52:12.895  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket.emit (events.js:315:20)
2021-04-03 10:52:12.895  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket.EventEmitter.emit (domain.js:467:12)
2021-04-03 10:52:12.896  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket._onTimeout (net.js:483:8)
2021-04-03 10:52:12.896  - error: host.VMC123-iobroker Caught by controller[1]:     at listOnTimeout (internal/timers.js:554:17)
2021-04-03 10:52:12.896  - error: host.VMC123-iobroker Caught by controller[1]:     at processTimers (internal/timers.js:497:7)
2021-04-03 10:52:12.896  - error: host.VMC123-iobroker instance system.adapter.tuya.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-04-03 10:52:44.596  - error: tuya.0 (35986) 037071752462ab4bdced: connect ECONNRESET 192.168.7.28:6668
2021-04-03 10:52:49.603  - error: tuya.0 (35986) bf72e9be420184d658hjd0: connection timed out
2021-04-03 10:52:49.603  - error: tuya.0 (35986) bf72e9be420184d658hjd0: connection timed out

`

**Comment by Apollon77** [comment]
Sorry, I can not do anything here: caused by https://github.com/codetheweb/tuyapi/issues/429

This in fact are device timeout cases ...

**Comment by Ilovegym66** [comment]
ah, read, ok.
