### ISSUE TITLE
tuya Instanz stoppt bei Timeout

### ISSUE THREAD

**Issue by ArnoD15** [Apollon77/ioBroker.tuya#327]
Ich habe heute die neue Version 3.6.11 getestet und immer noch den Fehler das die tuya Instanz gestoppt wird, wenn keine W-LAN Verbindung zu meiner Wärmepumpe möglich ist.
Wenn ich noch was testen soll um den Fehler einzugrenzen kann ich das gerne machen.

LOG Eintrag:

2021-09-09 11:15:23.306  - error: tuya.0 (31697) 281020088caab54df437: connection timed out
2021-09-09 11:15:53.339  - error: tuya.0 (31697) 281020088caab54df437: connection timed out
2021-09-09 11:16:13.258  - error: tuya.0 (31697) 281020088caab54df437: connection timed out
2021-09-09 11:16:28.202  - error:  tuya.0 (31697) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2021-09-09 11:16:28.203  - error: tuya.0 (31697) unhandled promise rejection: connection timed out
2021-09-09 11:16:28.203  - error: tuya.0 (31697) Error: connection timed out
at Socket. (/opt/iobroker/node_modules/tuyapi/index.js:465:18)
at Object.onceWrapper (events.js:420:28)
at Socket.emit (events.js:314:20)
at Socket._onTimeout (net.js:483:8)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
2021-09-09 11:16:28.204  - error: tuya.0 (31697) connection timed out
2021-09-09 11:16:28.229  - error: tuya.0 (31697) 281020088caab54df437: connection timed out
2021-09-09 11:16:29.827  - error: host.iobroker instance system.adapter.tuya.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-09-09 11:16:29.831  - info: host.iobroker Restart adapter system.adapter.tuya.0 because enabled
2021-09-09 11:16:59.985  - info: host.iobroker instance system.adapter.tuya.0 started with pid 8813
2021-09-09 11:17:11.916  - error: tuya.0 (8813) 281020088caab54df437: connection timed out
2021-09-09 11:17:38.271  - error: tuya.0 (8813) 281020088caab54df437: connection timed out
2021-09-09 11:19:43.291  - error: tuya.0 (8813) 281020088caab54df437: connection timed out
2021-09-09 11:20:00.392  - info: host.iobroker instance system.adapter.dwd.0 started with pid 8979
2021-09-09 11:20:07.987  - info: host.iobroker instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-09-09 11:20:48.237  - error: tuya.0 (8813) 281020088caab54df437: connection timed out
2021-09-09 11:21:12.666  - info:  synology.0 (22606) State value to set for  "synology.0.DiskStationManager.vol_info.volume_1.used_size" has to be  type "number" but received type "string"
2021-09-09 11:21:12.667  - info:  synology.0 (22606) State value to set for  "synology.0.DiskStationManager.vol_info.volume_1.used" has to be type  "number" but received type "string"
2021-09-09 11:24:03.164  - error: tuya.0 (8813) 281020088caab54df437: connection timed out
2021-09-09 11:24:15.184  - error:  tuya.0 (8813) Unhandled promise rejection. This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
2021-09-09 11:24:15.184  - error: tuya.0 (8813) unhandled promise rejection: connection timed out
2021-09-09 11:24:15.185  - error: tuya.0 (8813) Error: connection timed out
at Socket. (/opt/iobroker/node_modules/tuyapi/index.js:465:18)
at Object.onceWrapper (events.js:420:28)
at Socket.emit (events.js:314:20)
at Socket._onTimeout (net.js:483:8)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
2021-09-09 11:24:15.186  - error: tuya.0 (8813) connection timed out
2021-09-09 11:24:16.841  - error: host.iobroker instance system.adapter.tuya.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-09-09 11:24:16.846  - info: host.iobroker Restart adapter system.adapter.tuya.0 because enabled
2021-09-09 11:24:46.904  - info: host.iobroker instance system.adapter.tuya.0 started with pid 9235
2021-09-09 11:25:00.082  - info: host.iobroker instance system.adapter.dwd.0 started with pid 9262
2021-09-09 11:25:11.847  - info: host.iobroker instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-09-09 11:25:48.151  - error: tuya.0 (9235) 281020088caab54df437: connection timed out
2021-09-09 11:26:15.165  - info:  synology.0 (22606) State value to set for  "synology.0.DiskStationManager.vol_info.volume_1.used_size" has to be  type "number" but received type "string"
2021-09-09 11:26:15.204  - info:  synology.0 (22606) State value to set for  "synology.0.DiskStationManager.vol_info.volume_1.used" has to be type  "number" but received type "string"
2021-09-09 11:27:24.232  - error:  tuya.0 (9235) Unhandled promise rejection. This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
2021-09-09 11:27:24.233  - error: tuya.0 (9235) unhandled promise rejection: connection timed out
2021-09-09 11:27:24.234  - error: tuya.0 (9235) Error: connection timed out
at Socket. (/opt/iobroker/node_modules/tuyapi/index.js:465:18)
at Object.onceWrapper (events.js:420:28)
at Socket.emit (events.js:314:20)
at Socket._onTimeout (net.js:483:8)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
2021-09-09 11:27:24.234  - error: tuya.0 (9235) connection timed out
2021-09-09 11:27:25.872  - error: host.iobroker instance system.adapter.tuya.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-09-09 11:27:25.878  - info: host.iobroker Restart adapter system.adapter.tuya.0 because enabled
2021-09-09 11:27:25.878  - warn: host.iobroker Do not restart adapter system.adapter.tuya.0 because restart loop detected

**Versions:**  
 - Adapter version: 3.6.11
 - JS-Controller version: 3.3.15
 - Node version: 12.22.4
 - Operating system: Linux

**Comment by Apollon77** [comment]
Also an sich ist eine reconnection Logik eingebaut. Bitte Adapter  auf Debug Log stellen und dann Fehler proviózieren undndas volle Log zeigen. Auch die Reconnection EInstellung beim adapter beachten. der ist im default auf 30 oder 60s ... also ggf so lange warten oder runtersetzen

**Comment by ArnoD15** [comment]
Seitdem ich den Debug Modus eingeschaltet habe, kann diesen Fehler nicht mehr reproduzieren.
Habe es heute mehrmals versucht und es kommt jetzt immer eine Time Out Warnung, was ja auch richtig ist.
Ich werde den Debug Modus jetzt mal eingeschaltet lassen und Morgen prüfen ob der Fehler noch mal auftritt.

Aktuell sieht das LOG so aus wenn die Verbindung unterbrochen ist:

2021-09-10 14:46:07.798  - debug: tuya.0 (2409) 281020088caab54df437 request data via get ...
2021-09-10 14:46:07.816  - debug:  tuya.0 (2409) 281020088caab54df437: Received data:  {"1":false,"2":"silence","102":33,"103":true,"104":0,"105":"warm","106":32,"107":18,"108":40,"115":0,"116":0}
2021-09-10 14:46:07.857  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.1  {"val":false,"ack":true,"ts":1631277967852,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1631277581571}
2021-09-10 14:46:07.884  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.2  {"val":0,"ack":true,"ts":1631277967852,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1630831983208}
2021-09-10 14:46:07.885  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.102  {"val":33,"ack":true,"ts":1631277967852,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1631276995145}
2021-09-10 14:46:07.885  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.103  {"val":true,"ack":true,"ts":1631277967852,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1624798626311}
2021-09-10 14:46:07.894  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.104  {"val":0,"ack":true,"ts":1631277967852,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1631270961371}
2021-09-10 14:46:07.895  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.105  {"val":1,"ack":true,"ts":1631277967852,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1624796729990}
2021-09-10 14:46:07.896  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.106  {"val":32,"ack":true,"ts":1631277967853,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1631258598328}
2021-09-10 14:46:07.896  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.107  {"val":18,"ack":true,"ts":1631277967853,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1624798626470}
2021-09-10 14:46:07.898  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.108  {"val":40,"ack":true,"ts":1631277967853,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1624798626494}
2021-09-10 14:46:07.898  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.115  {"val":0,"ack":true,"ts":1631277967853,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1631255408784}
2021-09-10 14:46:07.898  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.116  {"val":0,"ack":true,"ts":1631277967853,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1624796203762}
2021-09-10 14:46:29.600  - debug: tuya.0 (2409) 281020088caab54df437: Disconnected from device
2021-09-10 14:46:29.612  - debug:  tuya.0 (2409) stateChange tuya.0.281020088caab54df437.online  {"val":false,"ack":true,"ts":1631277989606,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1631277989606}
2021-09-10 14:46:29.626  - debug:  tuya.0 (2409) stateChange tuya.0.info.connection  {"val":false,"ack":true,"ts":1631277989606,"q":0,"from":"system.adapter.tuya.0","user":"system.user.admin","lc":1631277989606}
2021-09-10 14:46:29.668  - debug: tuya.0 (2409) connected set to false
2021-09-10 14:47:04.603  - warn: tuya.0 (2409) 281020088caab54df437: Error on Reconnectconnection timed out
2021-09-10 14:47:39.604  - warn: tuya.0 (2409) 281020088caab54df437: Error on Reconnectconnection timed out
2021-09-10 14:48:14.607  - warn: tuya.0 (2409) 281020088caab54df437: Error on Reconnectconnection timed out
2021-09-10 14:48:49.608  - warn: tuya.0 (2409) 281020088caab54df437: Error on Reconnectconnection timed out
2021-09-10 14:49:24.610  - warn: tuya.0 (2409) 281020088caab54df437: Error on Reconnectconnection timed out
2021-09-10 14:49:59.613  - warn: tuya.0 (2409) 281020088caab54df437: Error on Reconnectconnection timed out

**Comment by Apollon77** [comment]
Genau so sollte es auch sein :-) Also er versucht eine Zeit lang. danach "gibt er auf" und wartet auf das nächste UDP Paket um dann wieder zu starten

**Comment by ArnoD15** [comment]
Also bis jetzt ist der Fehler nicht mehr aufgetreten. 
Kann somit erst mal geschlossen werden.
Danke für deine Arbeit, kann man nicht oft genug loben. :-)
