### ISSUE TITLE
Unhandled promise rejection - Adapter Version 3.6.15

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.tuya#435]
if some devices are offline, the Adapters crashs:

2022-07-13 10:44:35.899  - error: tuya.0 (7247) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-07-13 10:44:35.899  - error: tuya.0 (7247) unhandled promise rejection: connection timed out
2022-07-13 10:44:35.901  - error: tuya.0 (7247) Error: connection timed out
    at Socket.<anonymous> (/opt/iobroker/node_modules/tuyapi/index.js:468:20)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2022-07-13 10:44:35.901  - error: tuya.0 (7247) connection timed out
2022-07-13 10:44:37.877  - error: host.VMC123-iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-13 10:44:37.877  - error: host.VMC123-iobroker Caught by controller[1]: Error: connection timed out
2022-07-13 10:44:37.877  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket.<anonymous> (/opt/iobroker/node_modules/tuyapi/index.js:468:20)
2022-07-13 10:44:37.877  - error: host.VMC123-iobroker Caught by controller[1]:     at Object.onceWrapper (node:events:641:28)
2022-07-13 10:44:37.877  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket.emit (node:events:527:28)
2022-07-13 10:44:37.877  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket.emit (node:domain:475:12)
2022-07-13 10:44:37.877  - error: host.VMC123-iobroker Caught by controller[1]:     at Socket._onTimeout (node:net:516:8)
2022-07-13 10:44:37.877  - error: host.VMC123-iobroker Caught by controller[1]:     at listOnTimeout (node:internal/timers:559:17)
2022-07-13 10:44:37.877  - error: host.VMC123-iobroker Caught by controller[1]:     at processTimers (node:internal/timers:502:7)
2022-07-13 10:44:37.877  - error: host.VMC123-iobroker instance system.adapter.tuya.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

**Comment by Apollon77** [comment]
Welche version der tuyapi lib hast du? 

/opt/iobroker/node_modules/tuyapi/package.json ... was steht da als "version"?

die 3.6.15 vom adapter sollte an sich die 7.2.1 mitbringen in der das gefixt sein sollte

**Comment by Ilovegym66** [comment]
sollte.. die Version ist 7.2.1, schau:
![image](https://user-images.githubusercontent.com/36229898/178940531-eb61805a-89d8-47bf-84a6-d24b50635c23.png)

**Comment by Apollon77** [comment]
Please try 3.7.0
