### ISSUE TITLE
Restart loop

### ISSUE THREAD

**Issue by AnTri** [Apollon77/ioBroker.tuya#499]
Hi,

after updating the adapter to v3.10.2, it constantly reboots until iobroker prevents this.

2022-12-14 17:54:46.317 - error: tuya.0 (27722) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-12-14 17:54:46.318 - error: tuya.0 (27722) unhandled promise rejection: Cannot read properties of undefined (reading 'ir_send')
2022-12-14 17:54:46.322 - error: tuya.0 (27722) TypeError: Cannot read properties of undefined (reading 'ir_send')
at initDeviceObjects (/opt/iobroker/node_modules/iobroker.tuya/main.js:743:22)
at TuyaDevice.handleNewData (/opt/iobroker/node_modules/iobroker.tuya/main.js:984:57)
at TuyaDevice.emit (node:events:513:28)
at TuyaDevice.emit (node:domain:489:12)
at TuyaDevice._packetHandler (/opt/iobroker/node_modules/tuyapi/index.js:787:12)
at /opt/iobroker/node_modules/tuyapi/index.js:619:39
at Array.forEach ()
at Socket. (/opt/iobroker/node_modules/tuyapi/index.js:615:15)
at Socket.emit (node:events:513:28)
at Socket.emit (node:domain:489:12)

**Versions:**  
 - Adapter version: v3.10.2
 - JS-Controller version: 4.0.23
 - Node version: v16.18.1
 - Operating system: Linux raspberrypi 5.10.103-v7l+

Thanks for your help...

**Comment by Apollon77** [comment]
Please try GitHub version. Should be fixed there and will be released later today as 3.11.0 :-) If you can check it would be cool

**Comment by AnTri** [comment]
Works! Thanks for the quick help and fixing!!
